version: '3.8'

services:
  nombre_de_mi_servicio_postgree:
    image: postgres:15
    container_name: products_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "6969:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
